# Generated by Django 4.0.4 on 2022-05-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_second', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
